//
//  ILLAddiLListViewController.m
//  iLList
//
//  Created by Jake Choi on 4/14/14.
//  Copyright (c) 2014 iLList. All rights reserved.
//

#import "ILLAddiLListViewController.h"
#import <Firebase/Firebase.h>
#import "ILLiLListModel.h"

@interface ILLAddiLListViewController ()
@property (weak, nonatomic) IBOutlet UILabel *label;
@property (weak, nonatomic) IBOutlet UITextField *illistTF;

@end

@implementation ILLAddiLListViewController
NSString* illistName;
- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view.
    [self.navigationController.navigationBar setBackgroundImage:[UIImage imageNamed:@"bannerGradient.png"] forBarMetrics:UIBarMetricsDefault];
    UIImage* logoImage = [UIImage imageNamed:@"illistLogo.png"];
    // UIImage* background = [UIImage imageNamed:@"backgroundForTable.png"];
    self.navigationItem.titleView = [[UIImageView alloc] initWithImage:logoImage];
    [self.view setBackgroundColor:[UIColor colorWithPatternImage:[UIImage imageNamed:@"backgroundForTable.png"]]];

}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    illistName = self.illistTF.text;
    [self setupFirebasePlaylist:illistName];
    [textField resignFirstResponder];
    [self.navigationController popViewControllerAnimated:YES];
    return YES;
}

// Setting up playlist in Firebase
-(void) setupFirebasePlaylist:(NSString *)playlistname{
    //create reference to Playlists table
    Firebase* playlistsRef = [[Firebase alloc] initWithUrl:@"https://illist.firebaseio.com/playlists"];
    
    //autogenerated playlists id
    Firebase* newPushPlaylistRef = [playlistsRef childByAutoId];
    
    
    
    //validate playlist name
    NSString *validatedPlaylistName = [[ILLiLListModel sharedModel] removeUnknownCharacters:playlistname];
    
    //Create Value of this newCategory
    NSDictionary *newCategoryValue = @{@"votes":@0,@"created_at":@([NSDate date].timeIntervalSince1970),@"name":validatedPlaylistName};
    
    // Added new playlist (auto generated id)
    [[newPushPlaylistRef childByAppendingPath:@"playlistInfo"] setValue:newCategoryValue];
    
    //create string to reference user's individual illists
    NSString *linkUsers = @"https://illist.firebaseio.com/users/";
    NSString *linkUserID = [[ILLiLListModel sharedModel] userID];
    linkUsers = [linkUsers stringByAppendingString:linkUserID];
    linkUsers = [linkUsers stringByAppendingString:@"/illists/"];
   
    //create reference to user's illists table
    Firebase* userRef = [[Firebase alloc] initWithUrl:linkUsers];
    
    // Added a playlist in user's illist
    [[userRef childByAppendingPath:newPushPlaylistRef.name] setValue:playlistname];
    
    /*
    users.id -> illist -> instead of the auto named id for the playlist, it 
     */
}

@end
