//
//  ILLAddiLListViewController.m
//  iLList
//
//  Created by Jake Choi on 4/14/14.
//  Copyright (c) 2014 iLList. All rights reserved.
//

#import "ILLAddiLListViewController.h"
#import <Firebase/Firebase.h>
#import "ILLiLListModel.h"

@interface ILLAddiLListViewController ()
@property (weak, nonatomic) IBOutlet UILabel *label;
@property (weak, nonatomic) IBOutlet UITextField *illistTF;

@end

@implementation ILLAddiLListViewController
NSString* illistName;
- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view.
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    illistName = self.illistTF.text;

    [self setupFirebasePlaylist];
    [textField resignFirstResponder];
    [self.navigationController popViewControllerAnimated:YES];
    return YES;
}

// Setting up playlist in Firebase
-(void) setupFirebasePlaylist{
    //create reference to Playlists table
    Firebase* playlistsRef = [[Firebase alloc] initWithUrl:@"https://illist.firebaseio.com/playlists"];
    
    //autogenerated playlists id
    Firebase* newPushPlaylistRef = [playlistsRef childByAutoId];
    
    //create string to reference user's individual illists
    NSString *linkUsers = @"https://illist.firebaseio.com/users/";
    NSString *linkUserID = [[ILLiLListModel sharedModel] userID];

    linkUsers = [linkUsers stringByAppendingString:linkUserID];
    linkUsers = [linkUsers stringByAppendingString:@"/illist/"];
   
    //create reference to user's illists table
    Firebase* userRef = [[Firebase alloc] initWithUrl:linkUsers];

    //autogenerated id to store playlists id
    Firebase* newPushUserRef = [userRef childByAutoId];
    [[newPushPlaylistRef childByAppendingPath:@"playlistName"] setValue:self.illistTF.text];
    //[newPushPlaylistRef setValue:self.illistTF.text];
    [newPushUserRef setValue:newPushPlaylistRef.name];
    
    
}

@end
